import Head from 'next/head';
// eslint-disable-next-line camelcase
import { Darker_Grotesque, Nunito_Sans } from 'next/font/google';
import { useIsClient } from 'usehooks-ts';
import styles from '@/styles/Home.module.scss';

import Navbar from '@/components/Navbar';
import Lead from '@/components/Lead';
import FormBox from '@/components/FormBox';
import Together from '@/components/Together';
import Results from '@/components/Results';
import Benefits from '@/components/Benefits';
import CTA from '@/components/CTA';
import Demo from '@/components/Demo';
import Integrations from '@/components/Integrations';
import Footer from '@/components/Footer';

const grotesque = Darker_Grotesque({
  variable: '--grotesque-font',
  subsets: ['latin'],
  weight: ['500', '700', '800', '900'],
  preload: true,
});

const nunito = Nunito_Sans({
  variable: '--nunito-font',
  subsets: ['latin'],
  weight: ['200', '300', '400', '600', '800'],
  preload: true,
});

export default function Home() {
  const isClient = useIsClient();

  if (!isClient) return null;

  return (
    <div id="home" className={`${grotesque.variable} ${nunito.variable}`}>
      <Head>
        <title>RD Station Marketing</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.svg" />
      </Head>

      <Navbar />

      <main className={`relative ${styles.main}`}>
        <Lead />

        <FormBox />

        <Together />

        <Results />

        <Benefits />

        <CTA />

        <Demo />

        <Integrations />

      </main>

      <Footer />
    </div>
  );
}
