import Head from 'next/head';
import Image from 'next/image';
import { Darker_Grotesque, Nunito_Sans } from 'next/font/google';
import styles from '@/styles/Home.module.scss';

const grotesque = Darker_Grotesque({
  variable: '--grotesque-font',
  // subsets: ['latin'],
  weight: ['300','400','500','600','700','800','900',],
  preload: false,
});
const nunito = Nunito_Sans({
  variable: '--nunito-font',
  // subsets: ['latin'],
  weight: ['200', '300','400','600','700','800','900',],
  preload: false,
});

export default function Home() {
  return (
    <>
      <Head>
        <title>RD Station Marketing</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <navbar className={styles.navbar}>
        <Image
          src="/logo-default.svg"
          alt="RD Station"
          // className={}
          width={100}
          height={24}
          priority
        />

        <Image
          src="/menu.svg"
          alt="menu"
          width={32}
          height={32}
        />
      </navbar>

      <main className={`${styles.main} ${grotesque.variable} ${nunito.variable}`}>

        <div className={styles.titleBlock}>
          <p className={styles.title}>
            Gere mais
            {' '}
            <span className={styles.highlight}>oportunidades</span>
            {' '}
            para seu negócio
          </p>
        </div>

        <p className={styles.description}>
          O RD Station Marketing é um software para sua empresa fazer campanhas melhores, nutrir Leads, gerar oportunidades comerciais qualificadas e alcançar mais resultados.
        </p>

        <div className={styles.formBox}>
          <p className={styles.formTitle}>
            Comece seus 10 dias de teste grátis do RD Station Marketing!
          </p>
          <p className={styles.formSub}>
            Não precisa cadastrar cartão de crédito. 😉
          </p>

          <hr className={styles.hr} />

          <form>
            <p className={styles.formLabel}>Diga, qual seu nome?</p>
            <input
              id="field-name"
              className={styles.formGeneral}
              type="text"
              name="name"
              placeholder='   Insira seu nome'
            />

            <p className={styles.formLabel}>Seu email de trabalho</p>
            <input
              id="field-email"
              className={styles.formGeneral}
              type="text"
              name="email"
              placeholder='   Insira seu e-mail'
            />

            <p className={styles.formLabel}>Seu email de trabalho</p>
            <input
              id="field-phone"
              className={styles.formGeneral}
              type="text"
              name="phone"
              placeholder='   Insira seu número de telefone com DDD'
            />

            <p className={styles.formLabel}>Seu cargo de ocupação</p>
            <select className={styles.formGeneral} name="job" id="field-job" placeholder='   Selecione seu cargo'>
              <option>"Sócio(a) / CEO / Proprietário(a)"</option>
              <option>"Diretor(a) de Vendas"</option>
              <option>"Diretor(a) de Marketing"</option>
              <option>"Diretor(a) Outras Áreas"</option>
              <option>"Gerente de Marketing"</option>
              <option>"Gerente de Vendas"</option>
              <option>"Coordenador(a)/Supervisor(a) de Marketing"</option>
              <option>"Coordenador(a)/Supervisor(a) de Vendas"</option>
              <option>"Analista/Assistente de Marketing"</option>
              <option>"Analista/Assistente de Vendas"</option>
              <option>"Vendedor(a) / Executivo(a) de Contas"</option>
              <option>"Estudante"</option>
              <option>"Outros Cargo</option>
            </select>

            <p className={styles.formLabel}>Crie uma senha</p>
            <input className={styles.formGeneral} type="password" name="" id="" />
            
            <p className={styles.formLabel}>Confirme sua senha</p>
            <input className={styles.formGeneral} type="password" name="" id="" />

            <p className={styles.formLabel}>Qual o site da sua empresa?</p>
            {/* Meu site é */}
            <input className={styles.formRadio} type="radio" name="site" id="" />

            <input className={styles.formGeneral} type="text" name="" id="" placeholder='   Insira o endereço do seu site'/>

            {/* Ainda não tenho site */}
            <input className={styles.formRadio} type="radio" name="site" id="" />

            <ul className={styles.formLegal}>
              <li>Ao criar minha conta estou de acordo com os <a href="#" target="_blank" rel="noopener noreferrer">termos de uso</a> do software e <a href="http://" target="_blank" rel="noopener noreferrer">política de privacidade.</a></li>
              <li>Ao preencher o formulário, concordo em receber comunicações de acordo com meus interesses.</li>
              <li>*Você pode alterar suas permissões de comunicação a qualquer tempo.</li>
            </ul>

            <button type="submit">criar minha conta</button>
          </form>
        </div>

        {/* <div className={styles.description}>
          <p>
            Get started by editing&nbsp;
            <code className={styles.code}>src/pages/index.js</code>
          </p>
          <div>
            <a
              href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
              target="_blank"
              rel="noopener noreferrer"
            >
              By{' '}
              <Image
                src="/vercel.svg"
                alt="Vercel Logo"
                className={styles.vercelLogo}
                width={100}
                height={24}
                priority
              />
            </a>
          </div>
        </div>

        <div className={styles.center}>
          <Image
            className={styles.logo}
            src="/next.svg"
            alt="Next.js Logo"
            width={180}
            height={37}
            priority
          />
          <div className={styles.thirteen}>
            <Image
              src="/thirteen.svg"
              alt="13"
              width={40}
              height={31}
              priority
            />
          </div>
        </div>

        <div className={styles.grid}>
          <a
            href="https://nextjs.org/docs?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Docs <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Find in-depth information about Next.js features and&nbsp;API.
            </p>
          </a>

          <a
            href="https://nextjs.org/learn?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Learn <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Learn about Next.js in an interactive course with&nbsp;quizzes!
            </p>
          </a>

          <a
            href="https://vercel.com/templates?framework=next.js&utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Templates <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Discover and deploy boilerplate example Next.js&nbsp;projects.
            </p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Deploy <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Instantly deploy your Next.js site to a shareable URL
              with&nbsp;Vercel.
            </p>
          </a>
        </div> */}
      </main>
    </>
  );
}
