import Head from 'next/head';
import Image from 'next/image';
import { Darker_Grotesque, Nunito_Sans } from 'next/font/google';
import styles from '@/styles/Home.module.scss';
import Button from '@/components/Button';
import Slide from '@/components/Slide';

const grotesque = Darker_Grotesque({
  variable: '--grotesque-font',
  // subsets: ['latin'],
  weight: ['300', '400', '500', '600', '700', '800', '900'],
  preload: false,
});

const nunito = Nunito_Sans({
  variable: '--nunito-font',
  // subsets: ['latin'],
  weight: ['200', '300', '400', '600', '700', '800', '900'],
  preload: false,
});

const benefits = [
  {
    icon: 'chart-line',
    title: 'Torne sua operação de Marketing Digital mais produtiva',
    content: 'Chega de usar várias ferramentas separadas e perder as informações no caminho! Somos o que chamam de ferramenta tudo-em-um: reunimos os principais recursos de Marketing Digital em um só lugar para sua operação ser mais eficaz.',
  },
  {
    icon: 'bullhorn',
    title: 'Crie facilmente campanhas que funcionam',
    content: 'É fácil usar o RD Station Marketing, porque suas funcionalidades são simples, mas poderosas, e contam com dezenas de modelos — como de Landing Pages, Pop-ups, emails — para diversas ocasiões e segmentos que você pode personalizar de acordo com a sua campanha.',
  },
  {
    icon: 'chart-network',
    title: 'Construa jornadas personalizadas e gere vendas em escala',
    content: 'Envie a mensagem certa na hora certa e construa jornadas personalizadas que geram até 5x mais conversões e guiam Leads até a compra. Automatize também suas tarefas e aumente a produtividade de Marketing e Vendas.',
  },
  {
    icon: 'star',
    title: 'Encontre automaticamente as melhores oportunidades',
    content: 'Conheça melhor seu público, de acordo com as informações capturadas nas suas páginas e formulários. Defina critérios para identificar automaticamente Leads com maior potencial de compra e envie para o comercial oportunidades qualificadas.',
  },
  {
    icon: 'chart-pie',
    title: 'Saia da incerteza e comprove resultados',
    content: 'Ao invés de fazer uma série de ações isoladas, sem saber qual funciona, junte as informações de todos os seus contatos e suas ações em diferentes canais com recursos de análise para provar que Marketing Digital traz mais vendas e clientes.',
  },
  {
    icon: 'globe',
    title: 'Suporte ágil e na sua língua',
    content: 'Nosso time de suporte técnico está disponível quando você precisar, com uma taxa de satisfação de 97% entre nossos clientes e um tempo médio de resolução de 6 horas. E o melhor: tudo isso em português.',
  },
];

const integrations = [
  {
    icon: 'rd-station-crm',
    label: 'RD Station CRM',
  },
  {
    icon: 'salesforce',
    label: 'Salesforce',
  },
  {
    icon: 'google',
    label: 'Google',
  },
  {
    icon: 'facebook',
    label: 'Facebook',
  },
  {
    icon: 'linkedin',
    label: 'Linkedin',
  },
  {
    icon: 'wordpress',
    label: 'Wordpress',
  },
  {
    icon: 'hotmart',
    label: 'Hotmart',
  },
  {
    icon: 'pagseguro',
    label: 'PagSeguro',
  },
  {
    icon: 'shopify',
    label: 'Shopify',
  },
  {
    icon: 'zapier',
    label: 'Zapier',
  },
];

const social = ['twitter', 'facebook', 'linkedin', 'instagram', 'youtube'];

export default function Home() {
  return (
    <>
      <Head>
        <title>RD Station Marketing</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.svg" />
      </Head>
      <navbar className={styles.navbar}>
        <Image
          src="/logo-default.svg"
          alt="RD Station"
          // className={}
          width={150}
          height={24}
          priority
        />

        <Image
          src="/icon/menu.svg"
          alt="menu"
          width={32}
          height={32}
        />
      </navbar>

      <main className={`${styles.main} ${grotesque.variable} ${nunito.variable}`}>

        <div className={styles.container}>
          <div className={styles.titleBlock}>
            <p className={styles.title}>
              Gere mais
              {' '}
              <span className={styles.highlight}>oportunidades</span>
              {' '}
              para seu negócio
            </p>
          </div>

          <p className={styles.description}>
            O RD Station Marketing é um software para sua empresa fazer campanhas melhores, nutrir Leads, gerar oportunidades comerciais qualificadas e alcançar mais resultados.
          </p>

          <div className={styles.formBox}>
            <p className={styles.formTitle}>
              Comece seus 10 dias de teste grátis do RD Station Marketing!
            </p>
            <p className={styles.formSub}>
              Não precisa cadastrar cartão de crédito. 😉
            </p>

            <hr className={styles.hr} />

            <form>
              <p className={styles.formLabel}>Diga, qual seu nome?</p>
              <input
                id="field-name"
                className={styles.formGeneral}
                type="text"
                name="name"
                placeholder="Insira seu nome"
              />

              <p className={styles.formLabel}>Seu email de trabalho</p>
              <input
                id="field-email"
                className={styles.formGeneral}
                type="text"
                name="email"
                placeholder="Insira seu e-mail"
              />

              <p className={styles.formLabel}>Seu email de trabalho</p>
              <input
                id="field-phone"
                className={styles.formGeneral}
                type="text"
                name="phone"
                placeholder="Insira seu número de telefone com DDD"
              />

              <p className={styles.formLabel}>Seu cargo de ocupação</p>
              <select className={styles.formGeneral} name="job" id="field-job">
                <option value="">Selecione seu cargo</option>
                <option>Sócio(a) / CEO / Proprietário(a)</option>
                <option>Diretor(a) de Vendas</option>
                <option>Diretor(a) de Marketing</option>
                <option>Diretor(a) Outras Áreas</option>
                <option>Gerente de Marketing</option>
                <option>Gerente de Vendas</option>
                <option>Coordenador(a)/Supervisor(a) de Marketing</option>
                <option>Coordenador(a)/Supervisor(a) de Vendas</option>
                <option>Analista/Assistente de Marketing</option>
                <option>Analista/Assistente de Vendas</option>
                <option>Vendedor(a) / Executivo(a) de Contas</option>
                <option>Estudante</option>
                <option>Outros Cargo</option>
              </select>

              <p className={styles.formLabel}>Crie uma senha</p>
              <input className={styles.formGeneral} type="password" name="" id="" />

              <p className={styles.formLabel}>Confirme sua senha</p>
              <input className={styles.formGeneral} type="password" name="" id="" />

              <p className={styles.formLabel}>Qual o site da sua empresa?</p>

              <div className={styles.radioWrapper}>
                <input className={styles.formRadio} type="radio" name="site" id="site" />
                <label htmlFor="site">Meu site é</label>
              </div>

              <input className={styles.formGeneral} type="text" name="" id="" placeholder="Insira o endereço do seu site" />

              <div className={styles.radioWrapper}>
                <input className={styles.formRadio} type="radio" name="site" id="no-site" />
                <label htmlFor="site">Ainda não tenho site</label>
              </div>

              <ul className={styles.formLegal}>
                <li>
                  Ao criar minha conta estou de acordo com os
                  {' '}
                  <a
                    href="http://"
                    target="_blank"
                    className={`${styles.a} ${styles.highlight}`}
                    rel="noreferrer"
                  >
                    termos de uso
                  </a>
                  {' '}
                  do software e
                  {' '}
                  <a
                    href="http://"
                    target="_blank"
                    className={`${styles.a} ${styles.highlight}`}
                    rel="noreferrer"
                  >
                    política de privacidade.
                  </a>
                </li>
                <li>Ao preencher o formulário, concordo em receber comunicações de acordo com meus interesses.</li>
                <li>*Você pode alterar suas permissões de comunicação a qualquer tempo.</li>
              </ul>

              <Button highlight className="w-full">criar minha conta</Button>
            </form>
          </div>
        </div>

        <div className={`${styles.together}`}>
          <p className={styles.contentTitle}>Estaremos juntos desde o primeiro passo!</p>

          <p className={styles.contentText}>
            Se você ainda não sabe como extrair o máximo das ações digitais, não tem problema. O
            {' '}
            <strong>RD Station Marketing</strong>
            {' '}
            é mais que uma ferramenta, nos importamos com os seus resultados.
          </p>

          <p className={styles.contentText}>
            <strong>Estaremos com você do planejamento até a prática!</strong>
          </p>
        </div>

        <div className={`${styles.results} ${styles.container}`}>
          <p className={styles.contentTitle}>Resultados previsíveis e mais clientes para sua empresa</p>

          <p className={styles.contentSub}>Torne sua atuação no Marketing Digital mais eficaz</p>

          <ul>
            <li>
              <p>
                <strong>Ferramentas intuitivas</strong>
                {' '}
                e com modelos prontos, vídeos explicativos e passo a passo guiado
              </p>
            </li>
            <li>
              <p>
                <strong>Implementação com especialistas</strong>
                {' '}
                focada em planejamento e prática (nos planos Marketing Pro e Enterprise)
              </p>
            </li>
            <li>
              <p>
                <strong>Time de especialistas em Sucesso do Cliente</strong>
                {' '}
                para apoiar na otimização da estratégia em cada fase da sua jornada (nos planos Marketing Pro e Enterprise)
              </p>
            </li>
            <li>
              <p>
                <strong>Suporte técnico</strong>
                {' '}
                em português, espanhol e inglês para tirar dúvidas,
                {' '}
                <strong>com 97% de satisfação</strong>
                {' '}
                entre nossos clientes
              </p>
            </li>
            <li>
              <p>
                <strong>Muito conteúdo educativo</strong>
                , eventos, cursos da
                {' '}
                <a href="http://" target="_blank" className={`${styles.a} ${styles.highlight}`} rel="noreferrer">RD University</a>
                {' '}
                e comunidades para você continuar evoluindo
              </p>
            </li>
          </ul>

          <Image
            src="/img-results.jpg"
            alt="Mulher escrevendo na lousa"
            className="py-5 w-full"
            width={600}
            height={600}
          />
        </div>

        {/* <div className={styles.description}>
          <p>
            Get started by editing&nbsp;
            <code className={styles.code}>src/pages/index.js</code>
          </p>
          <div>
            <a
              href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
              target="_blank"
              rel="noopener noreferrer"
            >
              By{' '}
              <Image
                src="/vercel.svg"
                alt="Vercel Logo"
                className={styles.vercelLogo}
                width={100}
                height={24}
                priority
              />
            </a>
          </div>
        </div>

        <div className={styles.center}>
          <Image
            className={styles.logo}
            src="/next.svg"
            alt="Next.js Logo"
            width={180}
            height={37}
            priority
          />
          <div className={styles.thirteen}>
            <Image
              src="/thirteen.svg"
              alt="13"
              width={40}
              height={31}
              priority
            />
          </div>
        </div>

        <div className={styles.grid}>
          <a
            href="https://nextjs.org/docs?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Docs <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Find in-depth information about Next.js features and&nbsp;API.
            </p>
          </a>

          <a
            href="https://nextjs.org/learn?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Learn <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Learn about Next.js in an interactive course with&nbsp;quizzes!
            </p>
          </a>

          <a
            href="https://vercel.com/templates?framework=next.js&utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Templates <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Discover and deploy boilerplate example Next.js&nbsp;projects.
            </p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Deploy <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Instantly deploy your Next.js site to a shareable URL
              with&nbsp;Vercel.
            </p>
          </a>
        </div> */}
      </main>

      <div className={`${grotesque.variable} ${nunito.variable}`}>
        <section className={styles.benefits}>
          <div className={styles.container}>
            <p className="title">
              A ferramenta de Automação de Marketing líder na América Latina
            </p>

            {
              benefits ? benefits.map((item) => (
                <Slide
                  icon={item.icon}
                  title={item.title}
                  content={item.content}
                />
              )) : null
            }

          </div>
        </section>

        <section className={styles.cta}>
          <div className={styles.container}>
            <p className="title">
              Por que mais de 25.000 empresas escolheram o RD Station?
            </p>
            <p className="content">
              Combinamos nossos produtos de Marketing e Vendas com pessoas que se importam com seus resultados e um ecossistema que apoia o seu negócio do planejamento à prática.
            </p>

            <Button highlight className="w-full">criar conta gratuita</Button>
          </div>
        </section>

        <section className={styles.demo}>
          <div className={styles.container}>
            <p className="title">
              Entenda melhor como o RD Station Marketing funciona na prática
            </p>

            <Button secondary className="w-full button">
              assista a demonstração
              {' '}
              {'>'}
            </Button>

            <Image
              className="w-full thumbnail"
              src="/img-video-thumbnail.jpg"
              alt="menu"
              width={424}
              height={238}
            />
          </div>
        </section>

        <section className={styles.integrations}>
          <div className={styles.container}>
            <p className="title">
              Torne sua operação de Marketing ainda mais poderosa
            </p>

            <p className="content">
              O RD Station Marketing se conecta as principais ferramentas nacionais e internacionais
            </p>

            <div className="brands-wrapper mx-auto">
              {
                integrations ? integrations.map((brand) => (
                  <div className="brand inline-block">
                    <img className="brand-icon mx-auto" src={`/brands/${brand.icon}.svg`} alt={brand.label} />
                    <p className="label text-center">{brand.label}</p>
                  </div>
                )) : null
              }
            </div>

            <Button className="button block mx-auto">
              criar conta gratuita
            </Button>
          </div>
        </section>

        <footer className={styles.footer}>
          <div className={styles.container}>
            <Image
              className="mx-auto"
              src="/logo-bw.svg"
              alt="RD Station"
              width={174}
              height={32}
            />

            <hr />

            <div className="social mx-auto w-[60%]">
              {
                social ? social.map((item) => (
                  <a href="#">
                    <img
                      className="social-icon"
                      src={`/social/${item}.svg`}
                      alt={item}
                    />
                  </a>
                )) : null
              }
            </div>

            <p className="legal">
              © 2021
              {' '}
              <strong>RD Station</strong>
              .
              {' '}
              <a className={styles.a} href="">Política de Privacidade</a>
              .
            </p>
          </div>
        </footer>
      </div>
    </>
  );
}
